---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

## Custom configuration
#
elasticsearch.username: "admin"
elasticsearch.password: "admin"
#elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.verificationMode: certificate
elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/ssl/root-ca.pem

#searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
